### ISSUE TITLE
Trouble with node conditions.js

### ISSUE THREAD

**Issue by centurion800** [Ladinn/RTSP-Utilities#1]
root@servak:~/RTSP-Utilities# node conditions.js
Running every 5 minutes.
Getting current conditions...
/root/RTSP-Utilities/conditions.js:32
            const temp = json.temp_f;
                             ^

TypeError: Cannot read property 'temp_f' of undefined
    at IncomingMessage.<anonymous> (/root/RTSP-Utilities/conditions.js:32:30)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
root@servak:~/RTSP-Utilities#

**Comment by millette** [comment]
@centurion800 See step 7 in the [readme](https://github.com/Ladinn/RTSP-Utilities/blob/master/README.md).

**Comment by loganmines** [comment]
Weather Underground is no longer providing free API keys, instead, they provide cloud based "Data Packages". Any chance of getting the new APIs integrated?

**Comment by SA7BNT** [comment]
After that Weather Underground no longer provides API keys for free, is it possible that some one can fix the conditions.js with 
[https://web.stanford.edu/group/csp/cs22/using-an-api.pdf](url)
or may be with 
[https://github.com/initialstate/wunderground-sensehat/wiki/Part-1.-How-to-Use-the-Dark-Sky-API](url)
Im absloutly not confirm with .js

Looking forward and hope some can fix the broken conditions.js

**Comment by tjeerdoo** [comment]
I noticed that http://api.wunderground.com/api/APIKETHERE/conditions/q/pws:IAMERSFO201

doesn't work

I found that https://api.weather.com/v2/pws/observations/current?stationId=IAMERSFO201&format=json&units=h&apiKey=APIKEYHERE

does give me back results, however, after changing the const url to

const url = 'https://api.weather.com/v2/pws/observations/current?stationId=' + pws + '&format=json&units=h&apiKey=' + apiKey + '.json';

I'm stuck there..
